version: "3.9"
services:
 phala-node:
  image: swr.cn-east-3.myhuaweicloud.com/phala/phala-poc4-node
  container_name: phala-node
  ports:
   - "9933:9933"
   - "9944:9944"
   - "30333:30333"
  environment:
   - NODE_NAME=""
  volumes:
   - "$HOME/phala-node-data:/root/data"
 phala-pruntime:
  image: swr.cn-east-3.myhuaweicloud.com/phala/phala-poc4-pruntime
  container_name: phala-pruntime
  ports:
   - "8000:8000"
  volumes:
   - "$HOME/phala-pruntime-data:/root/data"
  depends_on:
   - phala-node
  devices:
   - "/dev/sgx/enclave"
   - "/dev/sgx/provision"
 phala-phost:
  image: swr.cn-east-3.myhuaweicloud.com/phala/phala-poc4-phost
  container_name: phala-phost
  environment:
   - PRUNTIME_ENDPOINT=""
   - PHALA_NODE_WS_ENDPOINT=""
   - MNEMONIC=""
  depends_on:
   - phala-node
   - phala-pruntime
  restart: on-failure
  